{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Date\",\"Exercise\",\"Person\",\"Location\",\"Activities\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.963.0 (23.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "e3a355b1-44c2-427c-bbd9-4bf736f143f9",
        "fromColumn": "Date",
        "fromTable": "Date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_4a12eac1-e221-4662-9c7c-a0b68bd5e44f"
      },
      {
        "name": "c5505d8a-2872-4827-bbcd-0fa5dd27c44b",
        "fromColumn": "ExerciseID",
        "fromTable": "Activities",
        "toColumn": "ExerciseID",
        "toTable": "Exercise"
      },
      {
        "name": "97be990a-2bd4-4b04-8930-19074caaf872",
        "fromColumn": "PersonID",
        "fromTable": "Activities",
        "toColumn": "PersonID",
        "toTable": "Person"
      },
      {
        "name": "be2b60e2-bcec-4edf-b864-83ccc891dbf2",
        "fromColumn": "LocationID",
        "fromTable": "Activities",
        "toColumn": "LocationID",
        "toTable": "Location"
      },
      {
        "name": "2344d834-aaa2-4107-9e9b-aad744847020",
        "fromColumn": "DateID",
        "fromTable": "Activities",
        "toColumn": "DateID",
        "toTable": "Date"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "DateTableTemplate_a829b0df-9a9e-431c-b611-c3cd7953e5b9",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "13098303-909b-42c1-a191-5a2ea6720096",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "4fdc1d0a-fee7-4870-a373-7a55ef073912",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c1b8000f-9bc1-4ace-b51c-c986ee7305bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "1925292e-d874-4714-9f47-bab68ec3f216",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "7749578e-9a9a-4ebd-9c6d-356aa52d26b8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6f882be9-7298-4652-9ab7-9814e1260a64",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "3663f09d-e998-4c22-9904-c20f76df7496",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9065a718-0b0a-40ad-834a-9a834fe598bd",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7f43d6a3-6df0-46af-8068-4c276448a43b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d8acac8f-5f02-4faa-a6c5-dffd85806fda",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "3755fd12-0d3c-45e6-8335-5ef43266d0fb",
                "ordinal": 3
              }
            ],
            "lineageTag": "ab5f3f72-d68f-4fc5-b930-35d47ff0e91c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "acd5345a-9087-4ed9-99e3-0b626222264b",
        "partitions": [
          {
            "name": "DateTableTemplate_a829b0df-9a9e-431c-b611-c3cd7953e5b9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Date",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a0283177-b25c-49d6-8c4e-cd23126ef5a4",
            "sourceColumn": "DateID",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "de5af90a-030f-47c2-94f3-eac6de1f503a",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_4a12eac1-e221-4662-9c7c-a0b68bd5e44f"
                },
                "isDefault": true,
                "relationship": "e3a355b1-44c2-427c-bbd9-4bf736f143f9"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3194955f-6ca6-4075-8311-ed7df9c55584",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "97c7e55c-8724-48f1-be16-0acab6ba2679",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "92e3674e-ff1d-40a4-86ce-57091d92095b",
            "sourceColumn": "Day",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "447e6955-c64f-4e8b-907d-a1fcc2b2d28f",
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1ZAUomYSVDANi5sFwfJvL40u1LwY1k61RIJFQHugYjDY/edit#gid=0\"),",
                "    Date_Table = Source{[name=\"Date\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Date_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"DateID\", Int64.Type}, {\"Date\", type date}, {\"Year\", Int64.Type}, {\"Month\", Int64.Type}, {\"Day\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_4a12eac1-e221-4662-9c7c-a0b68bd5e44f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c8ac410f-83f2-41a7-8242-a74fb3ab32d6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "aed5b848-1c6a-4cae-8b01-7bb8657c0109",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "c7e40721-df9f-4e73-856c-80ebbfbe916f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6152c7ce-4964-4f8c-b4e3-459ff9a20d60",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "f5dd0549-b820-4894-9559-ee350dc916a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "da3419ad-f40c-4bf2-b756-b5b8ade8cdde",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "bf3f6432-bade-4c13-8424-0d813eb9a7e7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "68750c03-f495-454a-ac0f-c863e499231a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "6ea61755-c1fe-4b35-95db-84bd63014d87",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "d1e0ac0d-090a-46c1-b0cc-bbf8e837e908",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "dcdc7d83-ce3f-4d35-8e15-487cce17c3db",
                "ordinal": 3
              }
            ],
            "lineageTag": "1fbe02a0-108c-4c6b-866e-5752126acd68"
          }
        ],
        "isHidden": true,
        "lineageTag": "1688855a-9206-46b9-ba45-4546ebca9401",
        "partitions": [
          {
            "name": "LocalDateTable_4a12eac1-e221-4662-9c7c-a0b68bd5e44f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Date'[Date])), 1, 1), Date(Year(MAX('Date'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Exercise",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ExerciseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "51b895b8-c293-4839-9efa-268d2e68ffed",
            "sourceColumn": "ExerciseID",
            "summarizeBy": "none"
          },
          {
            "name": "Exercise",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff0e8bbe-f13f-4937-9e16-da91e5b6be13",
            "sourceColumn": "Exercise",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4950af81-0977-4feb-9fda-a9afa49ac059",
        "partitions": [
          {
            "name": "Exercise",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1ZAUomYSVDANi5sFwfJvL40u1LwY1k61RIJFQHugYjDY/edit#gid=0\"),",
                "    Exercise_Table = Source{[name=\"Exercise\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Exercise_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ExerciseID\", Int64.Type}, {\"Exercise\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Person",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "PersonID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "99629d54-a284-4b96-ac31-7768f0edb8fc",
            "sourceColumn": "PersonID",
            "summarizeBy": "none"
          },
          {
            "name": "FirstName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "40a0f6fd-36b4-438f-af8a-89ef10bbd7a4",
            "sourceColumn": "FirstName",
            "summarizeBy": "none"
          },
          {
            "name": "LastName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89a61302-4691-485c-ad6f-ffb7cfc80cf5",
            "sourceColumn": "LastName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d5428e3c-8beb-4b1c-8522-eb028367afec",
        "partitions": [
          {
            "name": "Person",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1ZAUomYSVDANi5sFwfJvL40u1LwY1k61RIJFQHugYjDY/edit#gid=0\"),",
                "    Person_Table = Source{[name=\"Person\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Person_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"PersonID\", Int64.Type}, {\"FirstName\", type text}, {\"LastName\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Location",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "LocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3e1b4d52-5b72-440e-9ac8-35c819e5bb14",
            "sourceColumn": "LocationID",
            "summarizeBy": "none"
          },
          {
            "name": "Location",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd80d473-7f31-41f6-9138-f4ad1db187db",
            "sourceColumn": "Location",
            "summarizeBy": "none"
          },
          {
            "name": "Route",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a108c380-2b72-47ed-b81d-84521ef02426",
            "sourceColumn": "Route",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d53ec490-4533-4a04-a593-7933b7531a17",
        "partitions": [
          {
            "name": "Location",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1ZAUomYSVDANi5sFwfJvL40u1LwY1k61RIJFQHugYjDY/edit#gid=0\"),",
                "    Location_Table = Source{[name=\"Location\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Location_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"LocationID\", Int64.Type}, {\"Location\", type text}, {\"Route\", type text}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Activities",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "ActivityID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59d42c18-4db8-4095-a984-06fe1488fb14",
            "sourceColumn": "ActivityID",
            "summarizeBy": "count"
          },
          {
            "name": "DateID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0cd16faf-b21f-4fb4-8fa9-7e15f726d28c",
            "sourceColumn": "DateID",
            "summarizeBy": "none"
          },
          {
            "name": "PersonID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "238a5e9e-9e13-4364-82ba-1ddb85df0060",
            "sourceColumn": "PersonID",
            "summarizeBy": "none"
          },
          {
            "name": "LocationID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f32ef684-1320-4466-845b-01732cb7ae8a",
            "sourceColumn": "LocationID",
            "summarizeBy": "none"
          },
          {
            "name": "ExerciseID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "18059e75-54f9-4b48-84a0-ec10f6f4dd1c",
            "sourceColumn": "ExerciseID",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7b8effca-c720-41f1-a4a8-43fe3f91e34f",
        "partitions": [
          {
            "name": "Activities",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = GoogleSheets.Contents(\"https://docs.google.com/spreadsheets/d/1ZAUomYSVDANi5sFwfJvL40u1LwY1k61RIJFQHugYjDY/edit#gid=0\"),",
                "    Activities_Table = Source{[name=\"Activities\",ItemKind=\"Table\"]}[Data],",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Activities_Table, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"ActivityID\", Int64.Type}, {\"DateID\", Int64.Type}, {\"PersonID\", Int64.Type}, {\"LocationID\", Int64.Type}, {\"ExerciseID\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}